spring:
  data:
    mongodb:
      authentication-database: admin
      database: identity_manager
      username: trunk_cmon
      password: zlK0&hOF9voDRE+rO
      host: localhost
      port: 27017
      autoIndexCreation: true
    profiles:
      active: default
  security:
    oauth2:
      jwt:
        key: dRlSTuy9bIs3A*rot6EzIPRecLH
        issuer: https://trunkapi.com/idp
        audience: cia
        organization: trunk inc.
        expiry: 3600

logging:
  level:
    org:
      springframework: DEBUG
    com:
      trunk: INFO